export const MARKER_CREATE_REQUEST = "MARKER_CREATE_REQUEST";
export const MARKER_CREATE_SUCCESS = "MARKER_CREATE_SUCCESS";
export const MARKER_CREATE_FAIL = "MARKER_CREATE_FAIL";

export const MARKER_BY_USER_REQUEST = "MARKER_BY_USER_REQUEST";
export const MARKER_BY_USER_SUCCESS = "MARKER_BY_USER_SUCCESS";
export const MARKER_BY_USER_FAIL = "MARKER_BY_USER_FAIL";
